### ISSUE TITLE
Bug with "--format BlkText"

### ISSUE THREAD

**Issue by zarusoba10** [Warthunder-Open-Source-Foundation/wt_ext_cli#17]
When extracting vromfs and saving BLK using "--format BlkText", it will be saved in the wrong format in the following cases. This will cause problems with loading files that specify unit coordinates in custom hangars. Please fix this.

Correct notation  :  setting__tm:m = [[0.0709954, 0.0, 0.997477] [0.0, 1.0, 0.0] [-0.997477, 0.0, 0.0709954] [-5.5, 45.9, -632.3]]

Incorrect notation output by the program  :  setting__tm:m = [0.951579, 0.0, 0.307405, 0.0, 1.0, 0.0, -0.307405, 0.0, 0.951579, 368.05, 29.85, 611.35]

**Comment by FlareFlo** [comment]
[Upstream tracking issue](https://github.com/Warthunder-Open-Source-Foundation/wt_blk/issues/16)

**Comment by FlareFlo** [comment]
Can you provide the path to the file and line that encounters this issue specifically?

**Comment by zarusoba10** [comment]
The path to the file
game.vromfs.bin/gamedata/scenes/hangar_field_mission.blk

**Comment by zarusoba10** [comment]
Sorry, my original post was incorrect.
The bug I wanted to point out was not a mistake in the numbers, but a difference in the position of the [] signs.

Correct notation : setting__tm:m = [0.0709954, 0.0, 0.997477, 0.0, 1.0, 0.0, -0.997477, 0.0, 0.0709954, -5.5, 45.9, -632.3]
Incorrect notation output by the program : setting__tm:m=[[0.0709954, 0.0, 0.997477] [0.0, 1.0, 0.0] [-0.997477, 0.0, 0.0709954] [-5.5, 45.9, -632.3]]

**Comment by FlareFlo** [comment]
> Sorry, my original post was incorrect.
> The bug I wanted to point out was not a mistake in the numbers, but a difference in the position of the [] signs.
> 
> Correct notation : setting__tm:m = [0.0709954, 0.0, 0.997477, 0.0, 1.0, 0.0, -0.997477, 0.0, 0.0709954, -5.5, 45.9, -632.3]
> Incorrect notation output by the program : setting__tm:m=[[0.0709954, 0.0, 0.997477] [0.0, 1.0, 0.0] [-0.997477, 0.0, 0.0709954] [-5.5, 45.9, -632.3]]

I believe the above notation is incorrect as this data is a 3x4 transformation matrix, old unpacking tools displayed as one continuous array before. However i dont have an automotive source for this yet.

**Comment by zarusoba10** [comment]
When I ran kotiq's blk_unpack with the --format=strict_blk option, it outputted in double bracket format.
In fact, WT's custom hanger system will not read object placement information unless it's in double bracket format.

**Comment by FlareFlo** [comment]
> When I ran kotiq's blk_unpack with the --format=strict_blk option, it outputted in double bracket format. In fact, WT's custom hanger system will not read object placement information unless it's in double bracket format.

With double bracket you mean `[0.0709954, 0.0, 0.997477, 0.0, 1.0, 0.0, -0.997477, 0.0, 0.0709954, -5.5, 45.9, -632.3]`? If yes then i will adapt the formatting

**Comment by zarusoba10** [comment]
Yes, that's right. I would appreciate it if you could correct it. The bracket notation was my point.
I'm sorry that my poor expression bothered you.

**Comment by FlareFlo** [comment]
New repr (first line example)
```
entity {
        _template:t = "backmodel_spawn_point"
        transform:m = [[-0.0402914, 0.0, 0.999188], [-0.00392123, 0.995253, 0.0972426], [-0.994445, -0.0973217, -0.0401001], [397.934, 30.2243, 545.499]]
        spawnPointType:t = "plane"
        forPremiumVehicle:b = true
}
```
Just to ensure, is this correct?
