### ISSUE TITLE
Error when trying to use the blk unpacker

### ISSUE THREAD

**Issue by Hadiiiiiiiiiiiiii** [Warthunder-Open-Source-Foundation/wt_ext_cli#5]
when i try to run ".\wt_ext_cli.exe --unpack_raw_blk --input_dir C:\IdeaProjects\wt_ext_cli\target\release\blk\ "i get 
"thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\subcommands\unpack_raw_blk.rs:58:52"

in the blk folder i have some of the sample data from your other repo, is there something like a namemap or something else that you need for this blk unpacker?

**Comment by FlareFlo** [comment]
can you provide a view of the folder and command used?

**Comment by Hadiiiiiiiiiiiiii** [comment]
> can you provide a view of the folder and command used?

what do you mean by view exactly?
i have the [https://github.com/Warthunder-Open-Source-Foundation/wt_blk/blob/master/samples/su_r_27er.blk](r27-er.blk) in the blk folder and the command i used was "".\wt_ext_cli.exe --unpack_raw_blk --input_dir C:\IdeaProjects\wt_ext_cli\target\release\blk\"

**Comment by FlareFlo** [comment]
> 

This file requires a Name-map (nm) and dictionary (HEX-HASH.dict) to be unpacked, in the same folder as itself.

**Comment by Hadiiiiiiiiiiiiii** [comment]
where can i find those files?

**Comment by FlareFlo** [comment]
> where can i find those files?

the samples folder contains both a [nm](https://github.com/Warthunder-Open-Source-Foundation/wt_blk/blob/master/samples/nm) and a [dict](https://github.com/Warthunder-Open-Source-Foundation/wt_blk/blob/master/samples/bfb732560ad45234690acad246d7b14c2f25ad418a146e5e7ef68ba3386a315c.dict)

**Comment by Hadiiiiiiiiiiiiii** [comment]
hm, even after adding them im still getting a error, "
 [0s/0s] [###########################################################################################################################################>---------------------------------------------------------------------] 67% 2/3
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\subcommands\unpack_raw_blk.rs:130:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"

**Comment by FlareFlo** [comment]
i will run the sample files later and see whats the cause

**Comment by FlareFlo** [comment]
> hm, even after adding them im still getting a error, " [0s/0s] [###########################################################################################################################################>---------------------------------------------------------------------] 67% 2/3 thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\subcommands\unpack_raw_blk.rs:130:47 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"

Ob i believe i found the issue. The samples folder is a wild collection of differently versioned samples for static tests. I presume the tool runs over every file in the folder attempting to unpack incompatible files.

**Comment by FlareFlo** [comment]
Since there is no granular single-file mode right now, simply copy the .dict, nm and .blk into a separate folder.

**Comment by FlareFlo** [comment]
Using `--unpack_vromf` should cover this issue now
