### ISSUE TITLE
Unpack raw blk crash

### ISSUE THREAD

**Issue by Sgambe33** [Warthunder-Open-Source-Foundation/wt_ext_cli#8]
I tried unpacking a blk file I obtained. I placed it in a folder and then executed the following command:
`wt_ext_cli-windows-x86.exe --unpack_raw_blk --input_dir "PATH\TO\FOLDER"`
I get this error:
```The application panicked (crashed).
Message:  Ruh oh, looks like command args were bad
Location: src/subcommands/mod.rs:47

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  <empty backtrace>
```
  Is there a fix or the tool is not stable enough? Thanks

**Comment by FlareFlo** [comment]
The command layout for raw blk is currently disabled, but might be re-enabled in a later patch.
If youre looking to unpack just a vromf file alone that might be best right now.

**Comment by Sgambe33** [comment]
I fixed using kotiq tools with a custom patch. Thanks anyway
